/**
 * emoji-catalog.ts
 * Comprehensive, searchable emoji catalog for the account icon picker.
 * Each entry: { emoji, keywords } — keywords are in Spanish for es-AR search.
 */

export interface EmojiEntry {
  emoji: string
  keywords: string[]
}

export interface EmojiCategory {
  id: string
  label: string
  emojis: EmojiEntry[]
}

export const EMOJI_CATALOG: EmojiCategory[] = [
  {
    id: "money",
    label: "Dinero y finanzas",
    emojis: [
      { emoji: "💰", keywords: ["dinero", "plata", "bolsa", "money", "bag"] },
      { emoji: "💵", keywords: ["billete", "dolar", "efectivo", "dollar", "cash"] },
      { emoji: "💴", keywords: ["yen", "billete", "efectivo"] },
      { emoji: "💶", keywords: ["euro", "billete", "efectivo"] },
      { emoji: "💷", keywords: ["libra", "billete", "efectivo"] },
      { emoji: "💸", keywords: ["dinero", "volando", "gasto", "pago", "flying money"] },
      { emoji: "💳", keywords: ["tarjeta", "credito", "debito", "card"] },
      { emoji: "🪙", keywords: ["moneda", "coin", "peso"] },
      { emoji: "🏦", keywords: ["banco", "bank", "caja ahorro", "cuenta"] },
      { emoji: "🏛️", keywords: ["banco", "banco central", "gobierno", "cuenta corriente"] },
      { emoji: "📈", keywords: ["inversion", "grafico", "sube", "bolsa", "alza", "chart up"] },
      { emoji: "📉", keywords: ["baja", "grafico", "perdida", "chart down"] },
      { emoji: "📊", keywords: ["estadistica", "grafico", "barra", "chart"] },
      { emoji: "💹", keywords: ["inversion", "yen", "grafico"] },
      { emoji: "🏧", keywords: ["cajero", "atm", "banco", "retiro"] },
      { emoji: "🧾", keywords: ["recibo", "factura", "ticket", "receipt"] },
      { emoji: "📑", keywords: ["documento", "factura", "contrato"] },
      { emoji: "💼", keywords: ["maletin", "trabajo", "negocios", "briefcase"] },
      { emoji: "🤑", keywords: ["dinero", "plata", "codicia", "money face"] },
      { emoji: "💎", keywords: ["diamante", "lujo", "joya", "gem"] },
      { emoji: "🏆", keywords: ["trofeo", "premio", "meta", "logro"] },
      { emoji: "🎯", keywords: ["objetivo", "meta", "goal", "target"] },
      { emoji: "📋", keywords: ["lista", "presupuesto", "plan"] },
      { emoji: "🔐", keywords: ["seguro", "caja fuerte", "ahorro", "locked"] },
      { emoji: "🔒", keywords: ["bloqueado", "seguro", "candado"] },
      { emoji: "🏡", keywords: ["casa", "hipoteca", "hogar", "propiedad"] },
      { emoji: "🏠", keywords: ["casa", "hogar", "vivienda", "inmueble"] },
      { emoji: "🏢", keywords: ["edificio", "empresa", "oficina", "office"] },
      { emoji: "📦", keywords: ["caja", "paquete", "compra", "envio"] },
      { emoji: "🛒", keywords: ["carrito", "compras", "supermercado", "shopping"] },
    ],
  },
  {
    id: "smileys",
    label: "Caras y emociones",
    emojis: [
      { emoji: "😀", keywords: ["feliz", "contento", "alegre", "smiley"] },
      { emoji: "😊", keywords: ["feliz", "suave", "contento"] },
      { emoji: "😎", keywords: ["cool", "lentes", "genial", "sunglasses"] },
      { emoji: "🤩", keywords: ["estrella", "emocionado", "sorprendido"] },
      { emoji: "🥳", keywords: ["fiesta", "cumpleanos", "celebracion"] },
      { emoji: "😇", keywords: ["angel", "bueno", "halo"] },
      { emoji: "🤔", keywords: ["pensando", "duda", "think"] },
      { emoji: "😤", keywords: ["determinado", "orgulloso", "firm"] },
      { emoji: "💪", keywords: ["fuerza", "musculo", "motivacion"] },
      { emoji: "👊", keywords: ["punno", "golpe", "fuerza"] },
      { emoji: "✊", keywords: ["punno", "fuerza", "poder"] },
      { emoji: "🤜", keywords: ["punno derecha", "fuerza"] },
      { emoji: "🙌", keywords: ["aplauso", "celebracion", "hurra"] },
      { emoji: "👏", keywords: ["aplauso", "bravo"] },
      { emoji: "🙏", keywords: ["gracias", "ruego", "pray", "favor"] },
      { emoji: "👍", keywords: ["ok", "bien", "aprobado", "thumbs up"] },
      { emoji: "✌️", keywords: ["paz", "victoria", "dos"] },
      { emoji: "🤞", keywords: ["suerte", "dedos cruzados", "fingers crossed"] },
      { emoji: "🖐️", keywords: ["cinco", "hola", "mano"] },
      { emoji: "👋", keywords: ["hola", "adios", "wave", "saludo"] },
    ],
  },
  {
    id: "food",
    label: "Comida y bebida",
    emojis: [
      { emoji: "🍕", keywords: ["pizza", "comida", "food"] },
      { emoji: "🍔", keywords: ["hamburguesa", "burger", "comida rapida"] },
      { emoji: "🍟", keywords: ["papas fritas", "comida rapida", "fries"] },
      { emoji: "🌮", keywords: ["taco", "comida mexicana", "tortilla"] },
      { emoji: "🍣", keywords: ["sushi", "comida japonesa", "pescado"] },
      { emoji: "🍜", keywords: ["sopa", "fideos", "noodles", "ramen"] },
      { emoji: "🥗", keywords: ["ensalada", "sano", "verduras", "salad"] },
      { emoji: "🍱", keywords: ["bento", "almuerzo", "comida"] },
      { emoji: "🍰", keywords: ["torta", "pastel", "postre", "cake"] },
      { emoji: "🍩", keywords: ["dona", "postre", "donut"] },
      { emoji: "☕", keywords: ["cafe", "coffee", "bebida", "desayuno"] },
      { emoji: "🧋", keywords: ["bubble tea", "te", "bebida"] },
      { emoji: "🍺", keywords: ["cerveza", "beer", "bar", "salida"] },
      { emoji: "🍷", keywords: ["vino", "wine", "cena", "salida"] },
      { emoji: "🥂", keywords: ["brindar", "celebracion", "champan", "cheers"] },
      { emoji: "🧃", keywords: ["jugo", "juice", "bebida", "merienda"] },
      { emoji: "🍿", keywords: ["pochoclo", "cine", "popcorn"] },
      { emoji: "🥩", keywords: ["carne", "asado", "steak", "meat"] },
      { emoji: "🥓", keywords: ["bacon", "panceta", "desayuno"] },
      { emoji: "🍳", keywords: ["huevo", "desayuno", "cocinar", "egg"] },
      { emoji: "🥘", keywords: ["cocido", "guiso", "olla", "stew"] },
      { emoji: "🛒", keywords: ["supermercado", "compras", "shopping", "mercado"] },
      { emoji: "🥦", keywords: ["brocoli", "verdura", "sano"] },
      { emoji: "🍎", keywords: ["manzana", "fruta", "sano"] },
      { emoji: "🍓", keywords: ["frutilla", "fruta", "strawberry"] },
      { emoji: "🍇", keywords: ["uva", "fruta", "vino", "grape"] },
      { emoji: "🥑", keywords: ["palta", "avocado", "sano", "green"] },
      { emoji: "🥐", keywords: ["medialunas", "desayuno", "croissant"] },
      { emoji: "🧁", keywords: ["cupcake", "pasteleria", "postre"] },
    ],
  },
  {
    id: "transport",
    label: "Transporte",
    emojis: [
      { emoji: "🚗", keywords: ["auto", "car", "vehiculo", "transporte"] },
      { emoji: "🚕", keywords: ["taxi", "remis", "cab"] },
      { emoji: "🚙", keywords: ["suv", "auto", "4x4"] },
      { emoji: "🏎️", keywords: ["auto de carrera", "rapido", "sports car"] },
      { emoji: "🚓", keywords: ["policia", "patrullero", "police"] },
      { emoji: "🚑", keywords: ["ambulancia", "salud", "emergencia"] },
      { emoji: "🚒", keywords: ["bomberos", "emergencia"] },
      { emoji: "🚌", keywords: ["colectivo", "bus", "transporte publico"] },
      { emoji: "🚎", keywords: ["trolebús", "bus", "electrico"] },
      { emoji: "🚐", keywords: ["combi", "minibus", "van"] },
      { emoji: "🚂", keywords: ["tren", "ferrocarril", "locomotora"] },
      { emoji: "🚆", keywords: ["tren", "subte", "metro"] },
      { emoji: "🚇", keywords: ["subte", "metro", "subway"] },
      { emoji: "🚢", keywords: ["barco", "crucero", "ship"] },
      { emoji: "✈️", keywords: ["avion", "vuelo", "viaje", "airplane"] },
      { emoji: "🚀", keywords: ["cohete", "rocket", "espacio"] },
      { emoji: "🛸", keywords: ["ovni", "ufo", "nave espacial"] },
      { emoji: "🚁", keywords: ["helicoptero", "helicopter"] },
      { emoji: "⛵", keywords: ["velero", "barco", "sailboat"] },
      { emoji: "🛵", keywords: ["moto", "scooter", "delivery"] },
      { emoji: "🏍️", keywords: ["motocicleta", "moto", "motorcycle"] },
      { emoji: "🚲", keywords: ["bicicleta", "bike", "bici"] },
      { emoji: "🛴", keywords: ["monopatín", "scooter", "electrico"] },
      { emoji: "🛺", keywords: ["tuk-tuk", "rickshaw"] },
      { emoji: "⛽", keywords: ["nafta", "combustible", "gas", "gasolinera"] },
      { emoji: "🅿️", keywords: ["estacionamiento", "parking", "garaje"] },
      { emoji: "🗺️", keywords: ["mapa", "viaje", "map", "ruta"] },
    ],
  },
  {
    id: "home",
    label: "Hogar y vivienda",
    emojis: [
      { emoji: "🏠", keywords: ["casa", "hogar", "home", "vivienda"] },
      { emoji: "🏡", keywords: ["casa con jardin", "hogar", "alquiler", "hipoteca"] },
      { emoji: "🏢", keywords: ["edificio", "departamento", "office", "empresa"] },
      { emoji: "🏗️", keywords: ["construccion", "obra", "building"] },
      { emoji: "🏘️", keywords: ["barrio", "casas", "neighborhood"] },
      { emoji: "🛋️", keywords: ["sofa", "living", "mueble", "couch"] },
      { emoji: "🛏️", keywords: ["cama", "dormitorio", "bed"] },
      { emoji: "🚿", keywords: ["ducha", "bano", "higiene", "shower"] },
      { emoji: "🛁", keywords: ["banera", "bano", "bathe"] },
      { emoji: "🚽", keywords: ["inodoro", "bano", "toilet"] },
      { emoji: "🪥", keywords: ["cepillo dental", "higiene", "bano"] },
      { emoji: "🪴", keywords: ["planta", "decoracion", "naturaleza"] },
      { emoji: "🧹", keywords: ["escoba", "limpieza", "broom"] },
      { emoji: "🧺", keywords: ["canasto", "ropa", "lavado"] },
      { emoji: "🧻", keywords: ["papel higienico", "bano", "toilet paper"] },
      { emoji: "🧼", keywords: ["jabon", "limpieza", "soap"] },
      { emoji: "🧽", keywords: ["esponja", "limpieza", "sponge"] },
      { emoji: "🪟", keywords: ["ventana", "window", "vidrio"] },
      { emoji: "🚪", keywords: ["puerta", "door", "entrada"] },
      { emoji: "🔑", keywords: ["llave", "key", "acceso", "seguridad"] },
      { emoji: "🪑", keywords: ["silla", "mueble", "chair"] },
      { emoji: "🖼️", keywords: ["cuadro", "arte", "decoracion"] },
      { emoji: "📺", keywords: ["television", "tv", "entretenimiento"] },
      { emoji: "🖥️", keywords: ["computadora", "monitor", "escritorio"] },
      { emoji: "💡", keywords: ["luz", "lampara", "electricidad", "light"] },
      { emoji: "🔌", keywords: ["enchufe", "electricidad", "plugin"] },
      { emoji: "🛠️", keywords: ["herramienta", "arreglo", "reparacion", "tool"] },
      { emoji: "🪛", keywords: ["destornillador", "herramienta", "arreglo"] },
      { emoji: "🔧", keywords: ["llave inglesa", "herramienta", "wrench", "arreglo"] },
      { emoji: "🔨", keywords: ["martillo", "herramienta", "hammer", "construccion"] },
      { emoji: "🪏", keywords: ["pala", "shovel", "jardin", "herramienta", "construccion", "ahorro"] },
    ],
  },
  {
    id: "shopping",
    label: "Compras y ropa",
    emojis: [
      { emoji: "🛍️", keywords: ["bolsas", "compras", "shopping", "ropa"] },
      { emoji: "🛒", keywords: ["carrito", "supermercado", "compras"] },
      { emoji: "👕", keywords: ["remera", "ropa", "shirt", "tshirt"] },
      { emoji: "👗", keywords: ["vestido", "ropa", "dress"] },
      { emoji: "👔", keywords: ["camisa", "formal", "trabajo"] },
      { emoji: "👖", keywords: ["pantalon", "jean", "ropa", "pants"] },
      { emoji: "🧥", keywords: ["abrigo", "campera", "jacket", "coat"] },
      { emoji: "👟", keywords: ["zapatillas", "ropa deportiva", "sneakers"] },
      { emoji: "👠", keywords: ["zapatos taco", "elegante", "heels"] },
      { emoji: "👒", keywords: ["sombrero", "hat"] },
      { emoji: "🧢", keywords: ["gorra", "cap", "hat"] },
      { emoji: "👜", keywords: ["cartera", "bolso", "bag", "handbag"] },
      { emoji: "🎒", keywords: ["mochila", "backpack", "escuela"] },
      { emoji: "💍", keywords: ["anillo", "joya", "ring", "compromiso"] },
      { emoji: "👒", keywords: ["sombrero", "moda", "estilo"] },
      { emoji: "🧣", keywords: ["bufanda", "scarf", "invierno"] },
      { emoji: "🧤", keywords: ["guantes", "gloves", "invierno"] },
      { emoji: "🧦", keywords: ["medias", "socks"] },
      { emoji: "👓", keywords: ["anteojos", "lentes", "glasses"] },
      { emoji: "🕶️", keywords: ["lentes de sol", "sunglasses", "cool"] },
      { emoji: "⌚", keywords: ["reloj", "watch", "tiempo"] },
      { emoji: "💄", keywords: ["labial", "maquillaje", "lipstick", "belleza"] },
      { emoji: "💅", keywords: ["unas", "belleza", "manicura", "nails"] },
      { emoji: "🪞", keywords: ["espejo", "mirror", "bano"] },
      { emoji: "🧴", keywords: ["crema", "higiene", "cuidado", "lotion"] },
    ],
  },
  {
    id: "health",
    label: "Salud y bienestar",
    emojis: [
      { emoji: "🏥", keywords: ["hospital", "salud", "clinica"] },
      { emoji: "💊", keywords: ["pastilla", "medicamento", "pill", "medicina"] },
      { emoji: "💉", keywords: ["vacuna", "inyeccion", "syringe"] },
      { emoji: "🩺", keywords: ["medico", "doctor", "estetoscopio"] },
      { emoji: "🩹", keywords: ["curita", "vendaje", "bandage", "herida"] },
      { emoji: "🧬", keywords: ["dna", "biologia", "genetica"] },
      { emoji: "🔬", keywords: ["microscopio", "ciencia", "laboratorio"] },
      { emoji: "🧪", keywords: ["probeta", "quimica", "lab"] },
      { emoji: "🩻", keywords: ["radiografia", "rayos x", "xray"] },
      { emoji: "🏃", keywords: ["correr", "ejercicio", "running", "deporte"] },
      { emoji: "🧘", keywords: ["yoga", "meditacion", "relajacion"] },
      { emoji: "🏋️", keywords: ["gimnasio", "gym", "pesas", "fitness"] },
      { emoji: "🚴", keywords: ["ciclismo", "bicicleta", "deporte"] },
      { emoji: "🏊", keywords: ["natacion", "pileta", "swimming"] },
      { emoji: "⚽", keywords: ["futbol", "deporte", "soccer"] },
      { emoji: "🏀", keywords: ["basquet", "basketball", "deporte"] },
      { emoji: "🎾", keywords: ["tenis", "tennis", "deporte"] },
      { emoji: "🏐", keywords: ["voley", "volleyball", "deporte"] },
      { emoji: "🏈", keywords: ["futbol americano", "football", "deporte"] },
      { emoji: "🥊", keywords: ["boxeo", "boxing", "deporte"] },
      { emoji: "🧗", keywords: ["escalada", "climbing", "deporte"] },
      { emoji: "🤸", keywords: ["gimnasia", "deporte", "acrobacia"] },
      { emoji: "💆", keywords: ["masaje", "relajacion", "spa"] },
      { emoji: "🛀", keywords: ["bano", "relajacion", "bath"] },
      { emoji: "🌿", keywords: ["natural", "salud", "hierbas", "plant"] },
      { emoji: "🍃", keywords: ["hoja", "natural", "organico"] },
    ],
  },
  {
    id: "leisure",
    label: "Ocio y entretenimiento",
    emojis: [
      { emoji: "🎮", keywords: ["videojuego", "gaming", "gamer", "juego"] },
      { emoji: "🕹️", keywords: ["joystick", "videojuego", "gaming"] },
      { emoji: "🎲", keywords: ["dado", "juego de mesa", "board game"] },
      { emoji: "🃏", keywords: ["carta", "poker", "juego de cartas"] },
      { emoji: "🎭", keywords: ["teatro", "arte", "performance"] },
      { emoji: "🎨", keywords: ["arte", "pintura", "paleta", "art"] },
      { emoji: "🎬", keywords: ["cine", "pelicula", "movie", "claqueta"] },
      { emoji: "📽️", keywords: ["proyector", "cine", "pelicula"] },
      { emoji: "🎤", keywords: ["microfono", "musica", "canto", "karaoke"] },
      { emoji: "🎵", keywords: ["musica", "nota", "cancion", "music"] },
      { emoji: "🎶", keywords: ["musica", "melodia", "notas"] },
      { emoji: "🎸", keywords: ["guitarra", "musica", "rock", "guitar"] },
      { emoji: "🎹", keywords: ["piano", "musica", "keyboard"] },
      { emoji: "🎺", keywords: ["trompeta", "musica", "jazz"] },
      { emoji: "🥁", keywords: ["bateria", "drums", "musica"] },
      { emoji: "🎻", keywords: ["violin", "musica", "clasica"] },
      { emoji: "📚", keywords: ["libros", "lectura", "estudio", "books"] },
      { emoji: "📖", keywords: ["libro", "lectura", "read"] },
      { emoji: "📰", keywords: ["diario", "noticias", "news"] },
      { emoji: "🎪", keywords: ["circo", "fiesta", "espectaculo"] },
      { emoji: "🎡", keywords: ["calesita", "parque", "atracciones"] },
      { emoji: "🎢", keywords: ["montaña rusa", "parque", "aventura"] },
      { emoji: "🎠", keywords: ["calesita", "parque", "carrusel"] },
      { emoji: "🌟", keywords: ["estrella", "exito", "logro", "star"] },
      { emoji: "🎉", keywords: ["fiesta", "celebracion", "confeti", "party"] },
      { emoji: "🎊", keywords: ["celebracion", "fiesta", "confeti"] },
      { emoji: "🎁", keywords: ["regalo", "gift", "presente"] },
      { emoji: "🎀", keywords: ["cinta", "regalo", "bow"] },
      { emoji: "🏖️", keywords: ["playa", "vacaciones", "verano", "beach"] },
      { emoji: "⛷️", keywords: ["esqui", "nieve", "ski", "montaña"] },
    ],
  },
  {
    id: "objects",
    label: "Objetos y tecnología",
    emojis: [
      { emoji: "📱", keywords: ["celular", "smartphone", "telefono", "mobile"] },
      { emoji: "💻", keywords: ["computadora", "notebook", "laptop"] },
      { emoji: "🖥️", keywords: ["monitor", "desktop", "computadora"] },
      { emoji: "⌨️", keywords: ["teclado", "keyboard", "computadora"] },
      { emoji: "🖨️", keywords: ["impresora", "printer", "oficina"] },
      { emoji: "🖱️", keywords: ["mouse", "computadora", "raton"] },
      { emoji: "📷", keywords: ["camara", "foto", "photography"] },
      { emoji: "📸", keywords: ["camara flash", "foto", "selfie"] },
      { emoji: "📹", keywords: ["camara video", "film", "grabar"] },
      { emoji: "🎥", keywords: ["pelicula", "camara", "movie"] },
      { emoji: "📻", keywords: ["radio", "musica", "am fm"] },
      { emoji: "📠", keywords: ["fax", "oficina", "comunicacion"] },
      { emoji: "☎️", keywords: ["telefono fijo", "llamada"] },
      { emoji: "📞", keywords: ["auricular", "llamada", "telefono"] },
      { emoji: "⌚", keywords: ["reloj", "watch", "tiempo"] },
      { emoji: "🔋", keywords: ["bateria", "energia", "battery"] },
      { emoji: "🔌", keywords: ["enchufe", "electricidad", "plug"] },
      { emoji: "💿", keywords: ["cd", "disco", "musica"] },
      { emoji: "📀", keywords: ["dvd", "disco", "pelicula"] },
      { emoji: "🗜️", keywords: ["compresor", "archivo", "zip"] },
      { emoji: "💾", keywords: ["disco floppy", "guardar", "retro"] },
      { emoji: "📡", keywords: ["satelite", "antena", "comunicacion"] },
      { emoji: "🔭", keywords: ["telescopio", "astronomia", "ciencia"] },
      { emoji: "🔬", keywords: ["microscopio", "ciencia", "laboratorio"] },
      { emoji: "🧲", keywords: ["iman", "magnet", "atraer"] },
      { emoji: "💡", keywords: ["bombita", "idea", "luz", "electricidad"] },
      { emoji: "🔦", keywords: ["linterna", "luz", "flashlight"] },
      { emoji: "🕯️", keywords: ["vela", "luz", "candle", "romantico"] },
      { emoji: "🪫", keywords: ["bateria baja", "sin energia"] },
      { emoji: "🔑", keywords: ["llave", "acceso", "seguridad", "key"] },
      { emoji: "🗝️", keywords: ["llave vieja", "vintage", "acceso"] },
      { emoji: "🔐", keywords: ["candado llave", "seguro", "locked"] },
      { emoji: "🔒", keywords: ["candado", "bloqueado", "lock"] },
    ],
  },
  {
    id: "nature",
    label: "Naturaleza y clima",
    emojis: [
      { emoji: "🌍", keywords: ["mundo", "tierra", "earth", "planeta"] },
      { emoji: "🌎", keywords: ["americas", "mapa", "continente"] },
      { emoji: "🌏", keywords: ["asia", "oceania", "mapa"] },
      { emoji: "🌊", keywords: ["ola", "agua", "mar", "wave", "ocean"] },
      { emoji: "🏔️", keywords: ["montaña", "pico", "nevado", "mountain"] },
      { emoji: "🌲", keywords: ["arbol", "bosque", "tree", "pino"] },
      { emoji: "🌴", keywords: ["palmera", "tropical", "playa"] },
      { emoji: "🌵", keywords: ["cactus", "desierto", "seco"] },
      { emoji: "🌸", keywords: ["flor", "cerezo", "primavera", "sakura"] },
      { emoji: "🌺", keywords: ["hibisco", "flor", "tropical"] },
      { emoji: "🌻", keywords: ["girasol", "sunflower", "verano"] },
      { emoji: "🌹", keywords: ["rosa", "flor", "amor", "rose"] },
      { emoji: "☀️", keywords: ["sol", "sun", "calor", "verano"] },
      { emoji: "🌤️", keywords: ["sol con nubes", "clima"] },
      { emoji: "⛅", keywords: ["nublado", "sol", "nubes"] },
      { emoji: "🌧️", keywords: ["lluvia", "rain", "torment"] },
      { emoji: "⛈️", keywords: ["tormenta", "trueno", "lluvia"] },
      { emoji: "❄️", keywords: ["nieve", "frio", "invierno", "snow"] },
      { emoji: "🌈", keywords: ["arcoiris", "rainbow", "colorido"] },
      { emoji: "⚡", keywords: ["rayo", "lightning", "energia", "flash"] },
      { emoji: "🔥", keywords: ["fuego", "fire", "caliente", "hot"] },
      { emoji: "💧", keywords: ["gota", "agua", "drop", "water"] },
      { emoji: "🌊", keywords: ["ola", "wave", "playa"] },
      { emoji: "🌙", keywords: ["luna", "noche", "moon"] },
      { emoji: "⭐", keywords: ["estrella", "star", "brillante"] },
      { emoji: "🌟", keywords: ["estrella brillante", "star", "especial"] },
      { emoji: "🍀", keywords: ["trebol", "suerte", "clover"] },
      { emoji: "🌾", keywords: ["trigo", "campo", "siembra"] },
    ],
  },
  {
    id: "symbols",
    label: "Símbolos y señales",
    emojis: [
      { emoji: "❤️", keywords: ["corazon", "amor", "rojo", "heart"] },
      { emoji: "🧡", keywords: ["corazon naranja", "amor"] },
      { emoji: "💛", keywords: ["corazon amarillo", "amor"] },
      { emoji: "💚", keywords: ["corazon verde", "amor", "dinero"] },
      { emoji: "💙", keywords: ["corazon azul", "amor"] },
      { emoji: "💜", keywords: ["corazon violeta", "amor"] },
      { emoji: "🖤", keywords: ["corazon negro", "oscuro"] },
      { emoji: "🤍", keywords: ["corazon blanco", "amor"] },
      { emoji: "🤎", keywords: ["corazon marron", "amor"] },
      { emoji: "💯", keywords: ["cien", "perfecto", "100", "excelente"] },
      { emoji: "✅", keywords: ["check", "ok", "aprobado", "correcto"] },
      { emoji: "❎", keywords: ["no", "error", "x", "incorrecto"] },
      { emoji: "⚠️", keywords: ["advertencia", "alerta", "warning"] },
      { emoji: "🚨", keywords: ["alerta", "emergencia", "sirena"] },
      { emoji: "🆕", keywords: ["nuevo", "new"] },
      { emoji: "🔔", keywords: ["campana", "notificacion", "bell", "alerta"] },
      { emoji: "🔕", keywords: ["silencio", "mute", "no molestar"] },
      { emoji: "📢", keywords: ["altavoz", "anuncio", "megafono"] },
      { emoji: "💬", keywords: ["chat", "mensaje", "bubble", "comentario"] },
      { emoji: "📩", keywords: ["email", "mensaje", "inbox"] },
      { emoji: "📧", keywords: ["email", "correo", "mail"] },
      { emoji: "📫", keywords: ["correo", "buzón", "mail"] },
      { emoji: "🗓️", keywords: ["calendario", "fecha", "calendar"] },
      { emoji: "📅", keywords: ["calendario", "fecha", "schedule"] },
      { emoji: "⏰", keywords: ["alarma", "reloj", "alarm", "tiempo"] },
      { emoji: "⏱️", keywords: ["cronometro", "tiempo", "stopwatch"] },
      { emoji: "⌛", keywords: ["ampolleta", "tiempo", "hourglass"] },
      { emoji: "🔄", keywords: ["repetir", "renovar", "refresh", "sync"] },
      { emoji: "↗️", keywords: ["subir", "flecha arriba", "crecimiento"] },
      { emoji: "↘️", keywords: ["bajar", "flecha abajo", "descenso"] },
      { emoji: "🔁", keywords: ["repetir", "loop", "repeat"] },
      { emoji: "♻️", keywords: ["reciclar", "ecologico", "recycle"] },
      { emoji: "🌐", keywords: ["web", "internet", "mundo", "global"] },
      { emoji: "📍", keywords: ["ubicacion", "pin", "lugar", "location"] },
      { emoji: "🗺️", keywords: ["mapa", "viaje", "map"] },
    ],
  },
  {
    id: "animals",
    label: "Animales",
    emojis: [
      { emoji: "🐷", keywords: ["chancho", "cerdo", "ahorro", "pig", "alcancia"] },
      { emoji: "🐮", keywords: ["vaca", "cow", "granja"] },
      { emoji: "🐔", keywords: ["gallina", "pollo", "chicken", "granja"] },
      { emoji: "🐟", keywords: ["pescado", "fish", "mar"] },
      { emoji: "🦁", keywords: ["leon", "fuerza", "lion"] },
      { emoji: "🐯", keywords: ["tigre", "feroz", "tiger"] },
      { emoji: "🦊", keywords: ["zorro", "fox", "astuto"] },
      { emoji: "🐺", keywords: ["lobo", "wolf", "feroz"] },
      { emoji: "🐻", keywords: ["oso", "bear", "fuerte"] },
      { emoji: "🐼", keywords: ["panda", "oso panda", "china"] },
      { emoji: "🐧", keywords: ["pinguino", "penguin", "frio"] },
      { emoji: "🦅", keywords: ["aguila", "eagle", "vuelo"] },
      { emoji: "🦉", keywords: ["buho", "sabiduria", "owl"] },
      { emoji: "🐬", keywords: ["delfin", "dolphin", "mar"] },
      { emoji: "🐸", keywords: ["rana", "frog", "verde"] },
      { emoji: "🦋", keywords: ["mariposa", "butterfly", "transformacion"] },
      { emoji: "🌺", keywords: ["flor tropical", "hibisco", "hawaii"] },
      { emoji: "🦄", keywords: ["unicornio", "magico", "unicorn"] },
      { emoji: "🐉", keywords: ["dragon", "dragon", "fuego"] },
      { emoji: "🦈", keywords: ["tiburon", "shark", "feroz"] },
      { emoji: "🐳", keywords: ["ballena", "whale", "mar"] },
      { emoji: "🦜", keywords: ["loro", "parrot", "colorido"] },
    ],
  },
  {
    id: "travel",
    label: "Viajes y lugares",
    emojis: [
      { emoji: "🗽", keywords: ["estatua libertad", "nueva york", "usa"] },
      { emoji: "🗼", keywords: ["torre eiffel", "paris", "francia"] },
      { emoji: "🏰", keywords: ["castillo", "castle", "europeo"] },
      { emoji: "🏯", keywords: ["castillo japonés", "japon"] },
      { emoji: "⛩️", keywords: ["torii", "japon", "shinto"] },
      { emoji: "🕌", keywords: ["mezquita", "mosque", "isla"] },
      { emoji: "⛪", keywords: ["iglesia", "church", "religion"] },
      { emoji: "🛫", keywords: ["despegar", "vuelo", "viaje", "takeoff"] },
      { emoji: "🛬", keywords: ["aterrizar", "vuelo", "llegada"] },
      { emoji: "🌅", keywords: ["amanecer", "sunrise", "playa"] },
      { emoji: "🌆", keywords: ["ciudad de noche", "city", "downtown"] },
      { emoji: "🌇", keywords: ["ciudad al atardecer", "sunset city"] },
      { emoji: "🌃", keywords: ["ciudad de noche", "night city"] },
      { emoji: "🏖️", keywords: ["playa", "vacaciones", "verano", "beach"] },
      { emoji: "🏕️", keywords: ["camping", "carpa", "naturaleza"] },
      { emoji: "⛺", keywords: ["carpa", "camping", "tent"] },
      { emoji: "🏝️", keywords: ["isla", "tropical", "island"] },
      { emoji: "🌋", keywords: ["volcan", "volcano", "erupcion"] },
      { emoji: "🗻", keywords: ["monte fuji", "japon", "montaña nevada"] },
      { emoji: "🏔️", keywords: ["montaña nevada", "alpes", "mountain"] },
      { emoji: "🗺️", keywords: ["mapa", "viaje", "ruta", "map"] },
      { emoji: "🧳", keywords: ["maleta", "valija", "viaje", "luggage"] },
      { emoji: "🎫", keywords: ["entrada", "ticket", "evento"] },
      { emoji: "🎟️", keywords: ["entrada", "ticket", "evento"] },
      { emoji: "🏟️", keywords: ["estadio", "deporte", "futbol"] },
    ],
  },
  {
    id: "flags",
    label: "Banderas",
    emojis: [
      { emoji: "🇦🇷", keywords: ["argentina", "bandera argentina", "ar"] },
      { emoji: "🇺🇸", keywords: ["estados unidos", "usa", "estados unidos", "eeuu"] },
      { emoji: "🇧🇷", keywords: ["brasil", "brazil", "br"] },
      { emoji: "🇨🇱", keywords: ["chile", "cl"] },
      { emoji: "🇺🇾", keywords: ["uruguay", "uy"] },
      { emoji: "🇵🇾", keywords: ["paraguay", "py"] },
      { emoji: "🇪🇸", keywords: ["espana", "spain", "es"] },
      { emoji: "🇲🇽", keywords: ["mexico", "mx"] },
      { emoji: "🇨🇴", keywords: ["colombia", "co"] },
      { emoji: "🇵🇪", keywords: ["peru", "pe"] },
      { emoji: "🇪🇨", keywords: ["ecuador", "ec"] },
      { emoji: "🇧🇴", keywords: ["bolivia", "bo"] },
      { emoji: "🇻🇪", keywords: ["venezuela", "ve"] },
      { emoji: "🇨🇺", keywords: ["cuba", "cu"] },
      { emoji: "🇩🇴", keywords: ["republica dominicana", "do"] },
      { emoji: "🇩🇪", keywords: ["alemania", "germany", "de"] },
      { emoji: "🇫🇷", keywords: ["francia", "france", "fr"] },
      { emoji: "🇮🇹", keywords: ["italia", "italy", "it"] },
      { emoji: "🇬🇧", keywords: ["reino unido", "uk", "gb", "ingles"] },
      { emoji: "🇯🇵", keywords: ["japon", "japan", "jp"] },
      { emoji: "🇨🇳", keywords: ["china", "cn"] },
      { emoji: "🇨🇦", keywords: ["canada", "ca"] },
      { emoji: "🇦🇺", keywords: ["australia", "au"] },
      { emoji: "🇳🇱", keywords: ["holanda", "paises bajos", "nl"] },
      { emoji: "🇧🇪", keywords: ["belgica", "be"] },
      { emoji: "🇨🇭", keywords: ["suiza", "switzerland", "ch"] },
    ],
  },
]

/** Flatten all emojis with their category for search */
export const ALL_EMOJIS: (EmojiEntry & { categoryId: string })[] = EMOJI_CATALOG.flatMap(
  (cat) => cat.emojis.map((e) => ({ ...e, categoryId: cat.id }))
)

/** Search emojis by query (Spanish, case-insensitive) */
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return ALL_EMOJIS.filter(
    (e) =>
      e.emoji.includes(q) ||
      e.keywords.some((k) => k.includes(q))
  )
}
